# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Konnect < Formula
  desc "Konnect CLI – manage Kong Konnect from the command line"
  homepage "https://github.com/2eha0/toy-konnect-cli"
  version "0.1.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/2eha0/toy-konnect-cli/releases/download/v0.1.1/konnect_0.1.1_darwin_amd64.tar.gz"
      sha256 "8d7ac031bece73f82b1843ca8e2268b6a6117ba26f00dd1ac997ddde9b612ec0"

      define_method(:install) do
        bin.install "konnect"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/2eha0/toy-konnect-cli/releases/download/v0.1.1/konnect_0.1.1_darwin_arm64.tar.gz"
      sha256 "1b66d1863b9d2f9a222430d96180ceb12ee4d03f3a8df0507ec84b2f2de8828d"

      define_method(:install) do
        bin.install "konnect"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/2eha0/toy-konnect-cli/releases/download/v0.1.1/konnect_0.1.1_linux_amd64.tar.gz"
      sha256 "4343008be616c387f3104e6c9d55b1147ddbd58ea6e1243158f9de0ffb249119"
      define_method(:install) do
        bin.install "konnect"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/2eha0/toy-konnect-cli/releases/download/v0.1.1/konnect_0.1.1_linux_arm64.tar.gz"
      sha256 "897626b5fdab9dbb0faf65d50908d9cc6a482f296270f522cc22cdc99aa4730f"
      define_method(:install) do
        bin.install "konnect"
      end
    end
  end

  test do
    system "#{bin}/konnect", "--version"
  end
end
