# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Konnect < Formula
  desc "Konnect CLI – manage Kong Konnect from the command line"
  homepage "https://github.com/2eha0/toy-konnect-cli"
  version "0.1.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/2eha0/toy-konnect-cli/releases/download/v0.1.2/konnect_0.1.2_darwin_amd64.tar.gz"
      sha256 "66688391ee31041ecf28106731a5ece7b28fbdac40c669f0cdeb5dc1cf6340ef"

      define_method(:install) do
        bin.install "konnect"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/2eha0/toy-konnect-cli/releases/download/v0.1.2/konnect_0.1.2_darwin_arm64.tar.gz"
      sha256 "8df73d8e92d582ebb9ede632a6c4e74ef610201d7fea9b1f0acf6d3676092c57"

      define_method(:install) do
        bin.install "konnect"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/2eha0/toy-konnect-cli/releases/download/v0.1.2/konnect_0.1.2_linux_amd64.tar.gz"
      sha256 "68669ced35a35e831160446671d17871ed92673f6763acbd1f1fe27bd4b6bcbc"
      define_method(:install) do
        bin.install "konnect"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/2eha0/toy-konnect-cli/releases/download/v0.1.2/konnect_0.1.2_linux_arm64.tar.gz"
      sha256 "dd5e0a04814998e3b5e0036c6580c0beae32329346031151d84c3ca0a61b30ac"
      define_method(:install) do
        bin.install "konnect"
      end
    end
  end

  test do
    system "#{bin}/konnect", "--version"
  end
end
